apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: le-wildcard-issuer
spec:
  acme:
    # server: https://acme-staging-v02.api.letsencrypt.org/directory
    server: https://acme-v02.api.letsencrypt.org/directory
    email: unknownpgr@gmail.com
    privateKeySecretRef:
      name: le-wildcard-issuer
    solvers:
      - dns01:
          route53:
            region: ap-northeast-2
            accessKeyID: AKIASLXIZKRMHWH4M6VZ
            secretAccessKeySecretRef:
              name: secret-iam-route53
              key: secret-access-key
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-wildcard
spec:
  secretName: cert-wildcard
  dnsNames:
    - the-form.io
    - "*.the-form.io"
    - "*.staging.the-form.io"
  issuerRef:
    name: le-wildcard-issuer
    kind: ClusterIssuer
---
apiVersion: traefik.containo.us/v1alpha1
kind: TLSStore
metadata:
  name: default
  namespace: default
spec:
  defaultCertificate:
    secretName: cert-wildcard
