apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      imagePullSecrets:
        - name: ap-northeast-2-ecr-registry
      containers:
        - name: auth
          image: 162623214680.dkr.ecr.ap-northeast-2.amazonaws.com/server-auth:latest
          env:
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: secret-auth
                  key: client-id
            - name: CALLBACK_URL
              valueFrom:
                secretKeyRef:
                  name: secret-auth
                  key: callback-url
            - name: ROOT_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: secret-auth
                  key: root-domain
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: secret-auth
                  key: google-client-id
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: secret-auth
                  key: google-client-secret
            - name: GOOGLE_CALLBACK_URL
              valueFrom:
                secretKeyRef:
                  name: secret-auth
                  key: google-callback-url
          ports:
            - containerPort: 80
          livenessProbe:
            exec:
              command:
                - curl
                - --fail
                - https://auth.the-form.io
            failureThreshold: 3
            initialDelaySeconds: 15
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingress-auth
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`auth.the-form.io`)
      kind: Rule
      services:
        - name: auth
          port: 80
  tls: {}
