apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: 162623214680.dkr.ecr.ap-northeast-2.amazonaws.com/server-auth:latest
          envFrom:
          - secretRef:
              name: secret-auth
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: ap-northeast-2-ecr-registry
---
apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingress-auth
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`auth.the-form.io`)
      kind: Rule
      services:
        - name: auth
          port: 80
  tls: {}
