apiVersion: apps/v1
kind: Deployment
metadata:
  name: images
spec:
  replicas: 3
  selector:
    matchLabels:
      app: images
  template:
    metadata:
      labels:
        app: images
    spec:
      containers:
        - name: images
          image: 162623214680.dkr.ecr.ap-northeast-2.amazonaws.com/server-backend-images:latest
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: secret-images
                  key: aws_access_key_id_s3

            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-images
                  key: aws_secret_access_key_s3

            - name: STAGE
              valueFrom:
                secretKeyRef:
                  name: secret-images
                  key: stage

            - name: IMAGES_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: secret-images
                  key: images_db_host

            - name: IMAGES_DB_USER
              valueFrom:
                secretKeyRef:
                  name: secret-images
                  key: images_db_user

            - name: IMAGES_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-images
                  key: images_db_password

            - name: IMAGES_DB
              valueFrom:
                secretKeyRef:
                  name: secret-images
                  key: images_db

          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: images
spec:
  selector:
    app: images
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingress-images
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`images.the-form.io`)
      kind: Rule
      services:
        - name: images
          port: 80
  tls: {}
