apiVersion: apps/v1
kind: Deployment
metadata:
  name: images
spec:
  replicas: 1
  selector:
    matchLabels:
      app: images
  template:
    metadata:
      labels:
        app: images
    spec:
      imagePullSecrets:
        - name: ap-northeast-2-ecr-registry
      containers:
        - name: images
          image: 162623214680.dkr.ecr.ap-northeast-2.amazonaws.com/server-backend-images:latest
          envFrom:
            - secretRef:
                name: secret-images
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: 500Mi
              cpu: 200m
            requests:
              memory: 500Mi
              cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: images
spec:
  selector:
    app: images
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingress-images
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`images.the-form.io`)
      kind: Rule
      services:
        - name: images
          port: 80
  tls: {}
