apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingress-auth
spec:
  routes:
    - match: Host(`auth.staging.the-form.io`)
      kind: Rule
      services:
        - name: auth
          port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 1
