apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: secret-rdb
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: image-rdb
          resources:
            limits:
              memory: 500Mi
              cpu: 200m
            requests:
              memory: 500Mi
              cpu: 200m
      volumes:
        - name: image-rdb
          persistentVolumeClaim:
            claimName: image-rdb-pvc
