apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
          envFrom:
            - secretRef:
                name: secret-rdb
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: image-rdb
          resources:
            limits:
              memory: 500Mi
              cpu: 200m
            requests:
              memory: 500Mi
              cpu: 200m
      volumes:
        - name: image-rdb
          persistentVolumeClaim:
            claimName: image-rdb-pvc
