apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingress-frontend
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`the-form.io`)
      kind: Rule
      services:
        - name: frontend
          port: 80
  tls: {}
